### ISSUE TITLE
Uncaught Promise

### ISSUE THREAD

**Issue by jsquardo** [justTOBBI/nighttab#3]
Get this error...

`348:1 Uncaught (in promise) SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at setTheme (<anonymous>:30:24)
    at <anonymous>:1:1
setTheme @ VM278:30
(anonymous) @ VM347:1`

**Comment by nullishamy** [comment]
What did you pass into `setTheme`

**Comment by jsquardo** [comment]
> What did you pass into `setTheme`

setTheme("mocha","mauve")

**Comment by jsquardo** [comment]
Sorry I figured it out. I didn't have the tab page open like an idiot. Thank you!
